version: 2.1

orbs:
  github-maven-deploy: github-maven-deploy/github-maven-deploy@1.0.5
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@dev:alpha

workflows:
  build-and-test:
    jobs:
      - github-maven-deploy/build-and-test:
          mvn-build-test-command: mvn clean verify archetype:integration-test
          mvn-collect-artifacts-command: |
            mkdir -p ~/project/artifacts/junit/
            # no reporting files to collect from archetype:integration-test goal

  run-release:
    jobs:
      - approve-release:
          type: approval
          filters:
            branches:
              only: master
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - approve-release
          ssh-fingerprints: "8d:5d:f4:21:d2:b1:aa:52:93:de:2c:bf:43:ad:64:95"
          mvn-release-perform-command: mvn --batch-mode release:perform -s .circleci/.maven.xml
          context: rso-base
          filters:
            branches:
              only: master
