version: 2.1

orbs:
  maven: circleci/maven@1.4.1
  circleci-maven-release-orb: sonatype-nexus-community/circleci-maven-release-orb@0.0.20

release-args: &release-args
  ssh-fingerprints: "8d:5d:f4:21:d2:b1:aa:52:93:de:2c:bf:43:ad:64:95"
  context: rso-base
  filters:
    branches:
      only: main

jobs:
  build_and_test:
    docker:
      - image: 'cimg/openjdk:8.0'
    steps:
      - checkout
      - maven/with_cache:
          verify_dependencies: false
          steps:
            - run:
                name: Run Maven Build
                command: |
                  mvn clean --batch-mode verify archetype:integration-test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/project/artifacts/junit/
            # no reporting files to collect from archetype:integration-test goal
          when: always
      - store_test_results:
          path: ~/project/artifacts/junit
      - store_artifacts:
          path: ~/project/artifacts/it-reports

workflows:
  build-branch:
    jobs:
      - build_and_test:
          filters:
            branches:
              ignore: main

  run-release:
    jobs:
      - approve-release:
          type: approval
          filters:
            branches:
              only: main
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - approve-release
          <<: *release-args

  release-from-main:
    jobs:
      - build_and_test:
          filters:
            branches:
              only: main
      - circleci-maven-release-orb/run-maven-release:
          requires:
            - build_and_test
          <<: *release-args

